export type {
    WidgetInfo,
    CategoryInfo,
    ItemInfo,
    CustomWidgetType,
    CustomWidgetBase,
    CustomWidgetDef,
    ClockWidgetDef,
    WeatherWidgetDef,
    IframeWidgetDef,
    WindWidgetDef,
    GaugeWidgetDef,
    UniversalWidgetDef,
    PluginWidgetDef,
    BackendToGuiCommand,
    BackendToGuiCommandUpdate,
    BackendToGuiCommandAllUpdate,
    BackendToGuiCommandNavigate,
    BackendToGuiCommandDeviceDelete,
} from './base';
export type * from './common';
